---
# tasks file for mysql
# Install MySQL
- name: Install MySQL
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - python-mysqldb
    - python3-mysqldb
    - python-pymysql
    - python3-pymysql

- name: Generate new root password
  command: openssl rand -hex 7 creates=/root/.my.cnf
  register: mysql_new_root_password

- name: Remove anonymous users
  mysql_user: 
    name: ""
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_new_root_password.changed

- name: Remove test database
  mysql_db: 
    name: test 
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: mysql_new_root_password.changed

- name: Update root password
  mysql_user: 
    name: root 
    host: "{{ item }}" 
    password: "{{ mysql_new_root_password.stdout }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_password.changed

- name: Output the new password
  debug: msg="New root password is {{ mysql_new_root_password.stdout }}"
  when: mysql_new_root_password.changed
  
- name: Create the default.conf for MySQL
  template: src=my.conf dest=/root/.my.cnf
  when: mysql_new_root_password.changed