---
- hosts: all
  become: true
  roles:
    - role: adityaprakash_bobby.ansible_role_wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas6705
      wp_domain: book.example.com

  tasks:
    - name: Ping the machine
      ping:
