---
- hosts: all
  become: true
  roles:
    - role: adityaprakash_bobby.ansible_role_wordpress
      database_name: wordpress
      database_user: wordpress
      database_password: bananas6705
      wp_domain: book.example.com
      initial_post_title: Hey There
      initial_post_content: >
        This is an example content for the site.
        Change it as you like.

  tasks:
    - name: Ping the machine
      ping:
