---
- hosts: all
  become: true 
  tasks: 
    - name: "Ping machine"
      ping:

    - name: Install software-properties-common
      apt: name=software-properties-common state=installed

    # Add ppa for installing PHP 7
    - name: Add the ondrej PHP PPA
      apt_repository: repo='ppa:ondrej/php' 
    
    - name: Update the apt cache
      apt: update_cache=yes cache_valid_time=3600
    
    # Install PHP and remove apache
    - name: Install PHP
      apt: name={{item}} state=installed
      with_items:
      - php
      - php-fpm
      - php-mysql
      - php-xml
    
    - name: Remove apache
      apt: name=apache2 state=removed

    # Install MySQL
    - name: Install MySQL
      apt: name={{item}} state=installed
      with_items:
        - mysql-server
        - python-mysqldb
        - python-pymysql
    
    - name: Generate new root password
      command: openssl rand -hex 7 creates=/root/.default.conf
      register: mysql_new_root_password
    
    - name: Remove anonymous users
      mysql_user: name="" state=absent
      when: mysql_new_root_password.changed

    - name: Remove test database
      mysql_db: name=test state=absent
      when: mysql_new_root_password.changed
    
    - name: Update root password
      mysql_user: name=root host={{item}} password={{mysql_new_root_password.stdout}}
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost
      when: mysql_new_root_password.changed

    - name: Output the new password
      debug: msg="New root password is {{mysql_new_root_password.stdout}}"
      when: mysql_new_root_password.changed
      
    - name: Create the default.conf for MySQL
      template: src=templates/mysql/default.conf dest=/root/.default.conf
      when: mysql_new_root_password.changed
    
      # Install Nginx to serve the PHP application
    - name: Install Nginx
      apt: name=nginx state=installed
    
    - name: Start Nginx
      service: name=nginx state=started

    # - name: Create nginx config
    #   template: src=templates/nginx/default dest=/etc/nginx/sites-available/default
